# Generated by Django 3.2.18 on 2023-04-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230424_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['added_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
