# Generated by Django 3.2.18 on 2023-04-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230426_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='added_on',
            new_name='created_on',
        ),
    ]
