CAR_MAKER_CHOICES = (
    ('default', '------'),
    ('Acura', 'Acura'),
    ('Alfa Romeo', 'Alfa Romeo'),
    ('Aston Martin', 'Aston Martin'),
    ('Audi', 'Audi'),
    ('Bentley', 'Bentley'),
    ('BMW', 'BMW'),
    ('Buick', 'Buick'),
    ('Cadillac', 'Cadillac'),
    ('Chevrolet', 'Chevrolet'),
    ('Chrysler', 'Chrysler'),
    ('Cupra', 'Cupra'),
    ('Dodge', 'Dodge'),
    ('Ferrari', 'Ferrari'),
    ('Fiat', 'Fiat'),
    ('Ford', 'Ford'),
    ('Genesis', 'Genesis'),
    ('GMC', 'GMC'),
    ('Honda', 'Honda'),
    ('Hyundai', 'Hyundai'),
    ('Infiniti', 'Infiniti'),
    ('Jaguar', 'Jaguar'),
    ('Jeep', 'Jeep'),
    ('Kia', 'Kia'),
    ('Lamborghini', 'Lamborghini'),
    ('Land Rover', 'Land Rover'),
    ('Lexus', 'Lexus'),
    ('Lincoln', 'Lincoln'),
    ('Lotus', 'Lotus'),
    ('Maserati', 'Maserati'),
    ('Mazda', 'Mazda'),
    ('McLaren', 'McLaren'),
    ('Mercedes-Benz', 'Mercedes-Benz'),
    ('MG', 'MG'),
    ('Mini', 'Mini'),
    ('Mitsubishi', 'Mitsubishi'),
    ('Nissan', 'Nissan'),
    ('Pagani', 'Pagani'),
    ('Porsche', 'Porsche'),
    ('Ram', 'Ram'),
    ('Rolls-Royce', 'Rolls-Royce'),
    ('Seat', 'Seat'),
    ('Skoda', 'Skoda'),
    ('Subaru', 'Subaru'),
    ('Tesla', 'Tesla'),
    ('Toyota', 'Toyota'),
    ('Volkswagen', 'Volkswagen'),
    ('Volvo', 'Volvo')
)
