# Generated by Django 3.2.18 on 2023-05-09 15:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
